pretrained_model_path: "./outputs/astronaut"
image_path: "./data/astronaut"
prompt: "Astronaut is walking on the road"
prompts:
  - "Astronaut is walking on the moon"
  - "Astronaut is jumping on the moon"
eq_params:
  words:
    - 'jumping'
  values:
    - 10.0
save_name: "astronaut_jumping"

# editing guidance mask save
target_step: 21 # 1, 21, 41, 61, ...,
target_block: 'mid' # 'down', 'mid', 'up'
target_layer_dim: 1280  # down: 320, 640, 1280, mid: 1280, up: 1280, 640, 320
target_words: ['Astronaut', 'walking']
rgd: ['Astronaut'] # automatically, rgd = target_words - non_rgd

# dni
alpha: 0.9
beta: 0.9
gamma: 1.0 # overall editability higher values are effective

